In [4]:
import numpy as np
import pandas as pd


In [5]:
file=pd.read_csv("TechnoVerse_Fraudent_Data_CSV.csv")

In [6]:
file


ID Communication_Type                       Sender           Reciever  \
0      1              Phone         Welfare Organization         John Smith   
1      2              Email      welfare.org@example.com       Emma Johnson   
2      3              Phone              Welfare Support  Christopher Davis   
3      4              Email      welfarehelp@example.com      Olivia Wilson   
4      5              Phone         Welfare Organization     Ethan Thompson   
..   ...                ...                          ...                ...   
511  512              Email  welfare.support@example.com      Liam Thompson   
512  513              Phone              Welfare Support         Emma Davis   
513  514              Email      welfarehelp@example.com     Ethan Thompson   
514  515              Phone         Welfare Organization       Olivia Davis   
515  516              Email      welfare.org@example.com      Noah Thompson   

           Date                                            Content  Fraud  
0    02-12-2023  Hello John, we are calling to inform you about...      0  
1    05-06-2023  Dear Emma, we would like to notify you that yo...      0  
2    11-06-2023  Hello Christopher, we are calling to remind yo...      0  
3    18-06-2023  Dear Olivia, we have received your request for...      0  
4    08-06-2023  Hello Ethan, we are calling to inform you abou...      0  
..          ...                                                ...    ...  
511  02-06-2023  Dear Liam, we would like to inform you that yo...      0  
512  10-06-2023  Hello Emma, we are calling to remind you about...      0  
513  19-06-2023  Dear Ethan, we would like to inform you that y...      0  
514  08-06-2023  Hello Olivia, this is a courtesy call from the...      0  
515  24-06-2023  Dear Noah, we would like to inform you that ou...      0  

[516 rows x 7 columns]

In [7]:
x=file[['Content']]
y=file[['Fraud']]

In [8]:
x

Content
0    Hello John, we are calling to inform you about...
1    Dear Emma, we would like to notify you that yo...
2    Hello Christopher, we are calling to remind yo...
3    Dear Olivia, we have received your request for...
4    Hello Ethan, we are calling to inform you abou...
..                                                 ...
511  Dear Liam, we would like to inform you that yo...
512  Hello Emma, we are calling to remind you about...
513  Dear Ethan, we would like to inform you that y...
514  Hello Olivia, this is a courtesy call from the...
515  Dear Noah, we would like to inform you that ou...

[516 rows x 1 columns]

In [9]:
y

Fraud
0        0
1        0
2        0
3        0
4        0
..     ...
511      0
512      0
513      0
514      0
515      0

[516 rows x 1 columns]

In [78]:
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()
c = []
for i in range(0, len(file)):
    r=re.sub('[^a-zA-Z]', ' ',file['Content'][i])
    r=r.lower()
    r=r.split()

    r=[ps.stem(word) for word in r if not word in stopwords.words('english')]
    r=' '.join(r)
    c.append(r)
c

['hello john call inform upcom chang welfar program guidelin start next month revis elig criteria benefit amount question need clarif pleas contact offic thank attent',
 'dear emma would like notifi welfar benefit month june success process fund deposit design bank account within next busi day concern pleas let us know best regard xyz welfar organ',
 'hello christoph call remind upcom deadlin submit annual incom statement pleas ensur provid necessari document june th avoid disrupt benefit need assist question feel free contact offic thank',
 'dear olivia receiv request hous assist team current review applic notifi decis via mail within next month urgent concern pleas contact helplin thank patienc',
 'hello ethan call inform upcom workshop financi literaci money manag welfar program particip workshop held juli th commun center highli recommend attend gain valuabl insight tool better financi plan great day',
 'dear sophia would like inform request childcar assist approv start next month 

In [79]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer()
x = cv.fit_transform(c).toarray()
print(x)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.14210597 ... 0.14249924 0.         0.10521496]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.15930843 0.         0.1176261 ]
 [0.         0.         0.         ... 0.         0.         0.0758108 ]
 [0.         0.         0.         ... 0.09720454 0.         0.07177141]]


In [80]:
from sklearn.model_selection import train_test_split
x_t, x_test, y_t, y_test = train_test_split(x, y, test_size = 0.2, random_state = 7)

In [81]:
x_t

array([[0.        , 0.        , 0.        , ..., 0.15684241, 0.        ,
        0.1158053 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.11746734, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.15216379, 0.        ,
        0.11235082],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [82]:
from sklearn.naive_bayes import MultinomialNB
fraud_detect_model = MultinomialNB().fit(x_t, y_t)

y_pred=fraud_detect_model.predict(x_t)

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [83]:
y_pred

array([0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,

In [84]:
import matplotlib.pyplot as plt

In [85]:
from sklearn.metrics import confusion_matrix
print (confusion_matrix(y_pred,y_t))

[[279   0]
 [  0 133]]


In [86]:
from sklearn.metrics import classification_report

print(classification_report(y_pred, y_t))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       279
           1       1.00      1.00      1.00       133

    accuracy                           1.00       412
   macro avg       1.00      1.00      1.00       412
weighted avg       1.00      1.00      1.00       412



In [87]:
from sklearn import metrics
print(metrics.r2_score(y_pred,y_t))

1.0


In [95]:
s='I represent [Organization Name], and we are facing a severe crisis that demands immediate attention. We urgently require financial assistance to provide essential welfare services to the vulnerable members of our community. Our organization is actively working on the ground to identify those in dire need of support. We kindly request your generous contribution to help us provide food, shelter, and medical aid to those affected. Your donation will be used responsibly and with utmost transparency. Attached are official documents detailing the crisis and the urgency of intervention. Please review them and consider supporting our cause. Every contribution, no matter the amount, will make a significant difference in the lives of those affected. We sincerely appreciate your consideration and eagerly await your positive response.'
r=[]
p=re.sub('[^a-zA-Z]', ' ',s)
p = p.lower()
p = p.split()
p = [ps.stem(word) for word in p if not word in stopwords.words('english')]
p = ' '.join(p)

r.append(p)

z=cv.transform(r).toarray()
z

array([[0.        , 0.        , 0.        , 0.        , 0.13098926,
        0.        , 0.        , 0.        , 0.        , 0.40879568,
        0.        , 0.        , 0.        , 0.        , 0.17252928,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.0638797 , 0.        , 0.        ,
        0.16204621, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.17501725, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.12492974,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [96]:
y_pred_2=fraud_detect_model.predict(z)

In [97]:
y_pred_2

array([1], dtype=int64)